### ISSUE TITLE
ValueError: No JSON object could be decoded

### ISSUE THREAD

**Issue by avin-tokade** [rkferreira/nagios#5]
Hello ,

How to resolve below issue ?

[root@IN-MON-AP1 plugins]# ./check_unity.py -H 10.20.0.x -m battery -u icinga -p mypass
/usr/lib/python2.7/site-packages/urllib3/connectionpool.py:769: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
Traceback (most recent call last):
  File "./check_unity.py", line 573, in <module>
    main()
  File "./check_unity.py", line 526, in main
    value, descid, desc = getBattery(hostaddress, token, cookie)
  File "./check_unity.py", line 110, in getBattery
    j = json.loads(r.text)
  File "/usr/lib64/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by avin-tokade** [comment]
Does anyone have any idea about how to fix this ?

My System details
[root@ICINGA ~]# python -V
Python 2.7.5
[root@ICINGA ~]# cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.6 (Maipo)
